local Locales = {
    ["DODGE_CHANCE"] = {
        ["deDE"] = "Ausweichchance: ",
        ["enUS"] = "Dodge Chance: ",
        ["frFR"] = "Chances d'esquiver: ",
        ["zhCN"] = "躲闪几率: ",
    },
    ["RANGED_HIT_BONUS_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Bonus auf die Fernkampf Trefferwertung.",
        ["enUS"] = "Shows/Hides the ranged hit bonus.",
        ["frFR"] = "Affiche/cache le bonus de toucher à distance.",
        ["zhCN"] = "显示/隐藏 远程命中率",
    },
    ["SHOW_ITEM_QUALITY_COLORS_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die farbigen Ränder an ausgerüsteten Gegenständen.",
        ["enUS"] = "Shows/Hides the colored frames around equiped items.",
        ["frFR"] = "Affiche/cache le niveau de rareté des objets par un cadre coloré.",
        ["zhCN"] = "显示/隐藏 装备边框染色 。",
    },
    ["SPELL_PENETRATION_SETTING"] = {
        ["deDE"] = "Zauberdurchschlagskraft",
        ["enUS"] = "Spell Penetration",
        ["frFR"] = "Spell Penetration",
        ["zhCN"] = "Spell Penetration",
    },
    ["SHOW_ITEM_QUALITY_COLORS"] = {
        ["deDE"] = "Zeige Item Qualitätsfarben",
        ["enUS"] = "Show Item Quaility Colors",
        ["frFR"] = "Affiche la couleur de rareté des objets",
        ["zhCN"] = "显示物品等级颜色",
    },
    ["DEFENSE_VALUE"] = {
        ["deDE"] = "Verteidigung: ",
        ["enUS"] = "Defense: ",
        ["frFR"] = "Défense: ",
        ["zhCN"] = "防御: ",
    },
    ["MELEE_ATTACK_SPEED_SETTING"] = {
        ["deDE"] = "Angriffstempo",
        ["enUS"] = "Attack Speed",
        ["frFR"] = "Attack Speed",
        ["zhCN"] = "Attack Speed",
    },
    ["FROST_CRIT_SETTING"] = {
        ["deDE"] = "Frost Kritisch",
        ["enUS"] = "Frost Crit",
        ["frFR"] = "Critique du givre",
        ["zhCN"] = "冰霜暴击",
    },
    ["SPELL_POWER_STATS_SETTINGS_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt alle Zaubermachtwerte.",
        ["enUS"] = "Shows/Hides all spell power stats.",
        ["frFR"] = "Affiche/cache toutes les statistiques de puissance des sorts.",
        ["zhCN"] = "显示/隐藏 法术强度属性",
    },
    ["HOLY_DMG"] = {
        ["deDE"] = "Heiligschaden: ",
        ["enUS"] = "Holy Damage: ",
        ["frFR"] = "Dégats du sacré: ",
        ["zhCN"] = "神圣伤害: ",
    },
    ["SHADOW_CRIT_SETTING"] = {
        ["deDE"] = "Schatten Kritisch",
        ["enUS"] = "Shadow Crit",
        ["frFR"] = "Critique des ombres",
        ["zhCN"] = "暗影暴击",
    },
    ["EXPERTISE"] = {
        ["deDE"] = "Waffenkundewertung: ",
        ["enUS"] = "Expertise: ",
        ["frFR"] = "Expertise: ",
        ["zhCN"] = "Expertise: ",
    },
    ["MP5_SPIRIT"] = {
        ["deDE"] = "MP5 (Willenskraft): ",
        ["enUS"] = "MP5 (Spirit): ",
        ["frFR"] = "MP5 (Esprit): ",
        ["zhCN"] = "精神回蓝: ",
    },
    ["BLOCK_CHANCE"] = {
        ["deDE"] = "Blockchance: ",
        ["enUS"] = "Block Chance: ",
        ["frFR"] = "Chances de bloquer: ",
        ["zhCN"] = "格挡几率: ",
    },
    ["MISS_CHANCE_BOSS_SETTING"] = {
        ["deDE"] = "Chance zu verfehlen (Boss)",
        ["enUS"] = "Miss Chance Boss",
        ["frFR"] = "Ch. de rater-Boss",
        ["zhCN"] = "未命中 Boss",
    },
    ["PHYSICAL_CRIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance mit physischen Zaubern kritisch zu treffen.",
        ["enUS"] = "Shows/Hides the physical crit chance.",
        ["frFR"] = "Affiche/Cache les chances de critique physique.",
        ["zhCN"] = "显示/隐藏 物理暴击",
    },
    ["MELEE_ATTACK_SPEED_OFF_HAND_SETTING"] = {
        ["deDE"] = "Schildhand",
        ["enUS"] = "Off Hand",
        ["frFR"] = "Off Hand",
        ["zhCN"] = "Off Hand",
    },
    ["SPELL_HIT_SETTING"] = {
        ["deDE"] = "Zauber Trefferwertung",
        ["enUS"] = "Spell Hit",
        ["frFR"] = "Toucher des sorts",
        ["zhCN"] = "法术命中",
    },
    ["RANGED_MISS_CHANCE_BOSS_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance einen Gegner mit 3 Level über dem eigenen im Fernkampf zu verfehlen.",
        ["enUS"] = "Shows/Hides the ranged miss chance against boss enemies (+3 Level).",
        ["frFR"] = "Affiche/cache les chances de rater à distance contre un boss de 3 niveaux supérieurs.",
        ["zhCN"] = "显示/隐藏 针对BOSS的远程未命中率 (+3 等级)。",
    },
    ["STATS_WINDOW_CLOSED_DESC"] = {
        ["deDE"] = "Versteckt das Wertefenster beim Öffnen des Characterfensters.",
        ["enUS"] = "Hides the stats windows when opening the character tab.",
        ["frFR"] = "Cache la fenêtre des statistiques quand la section du personnage est ouverte.",
        ["zhCN"] = "显示ECS打开/关闭按键",
    },
    ["SLASH_TOGGLE"] = {
        ["deDE"] = "/ecs toggle",
        ["enUS"] = "/ecs toggle",
        ["frFR"] = "/ecs toggle",
        ["zhCN"] = "/ecs toggle",
    },
    ["MP5_CASTING"] = {
        ["deDE"] = "MP5 (Zaubernd): ",
        ["enUS"] = "MP5 (Casting): ",
        ["frFR"] = "MP5 (Lancer): ",
        ["zhCN"] = "附魔回蓝: ",
    },
    ["FROST_CRIT"] = {
        ["deDE"] = "Frost Kritisch: ",
        ["enUS"] = "Frost Crit: ",
        ["frFR"] = "Critique du givre: ",
        ["zhCN"] = "冰霜暴击: ",
    },
    ["SPELL_HIT_BONUS_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Bonus auf die Zauber Trefferwertung.",
        ["enUS"] = "Shows/Hides the spell hit bonus.",
        ["frFR"] = "Affiche/cache le bonus de toucher des sorts.",
        ["zhCN"] = "显示/隐藏 法术命中几率",
    },
    ["MANA"] = {
        ["deDE"] = "Mana",
        ["enUS"] = "Mana",
        ["frFR"] = "Mana",
        ["zhCN"] = "法力回复",
    },
    ["DEFENSE"] = {
        ["deDE"] = "Verteidigung",
        ["enUS"] = "Defense",
        ["frFR"] = "Défense",
        ["zhCN"] = "防御",
    },
    ["ARCANE_CRIT_SETTING"] = {
        ["deDE"] = "Arkan Kritisch",
        ["enUS"] = "Arcane Crit",
        ["frFR"] = "Critique des arcanes",
        ["zhCN"] = "奥术法术暴击",
    },
    ["DODGE_CHANCE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Ausweichchance.",
        ["enUS"] = "Shows/Hides the dodge chance.",
        ["frFR"] = "Affiche/cache les chances d'esquiver.",
        ["zhCN"] = "显示/隐藏 躲闪几率",
    },
    ["NATURE_DMG"] = {
        ["deDE"] = "Naturschaden: ",
        ["enUS"] = "Nature Damage: ",
        ["frFR"] = "Dégats de la nature: ",
        ["zhCN"] = "自然伤害: ",
    },
    ["CRIT_REDUCTION_SETTING"] = {
        ["deDE"] = "Krit. Reduzierung",
        ["enUS"] = "Crit Reduction",
        ["frFR"] = "Crit Reduction",
        ["zhCN"] = "Crit Reduction",
    },
    ["DEFENSE_SETTINGS"] = {
        ["deDE"] = "Verteidigungswerte anzeigen",
        ["enUS"] = "Show Defense Stats",
        ["frFR"] = "Défense Général",
        ["zhCN"] = "显示防御属性",
    },
    ["MELEE_SETTINGS_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt alle Nahkampfwerte.",
        ["enUS"] = "Shows/Hides all melee stats.",
        ["frFR"] = "Affiche/cache toutes les statistiques de mêlée.",
        ["zhCN"] = "显示/隐藏 所有近战属性",
    },
    ["STAT_FONT_SIZE"] = {
        ["deDE"] = "Werte Schriftgröße",
        ["enUS"] = "Stat Font Size",
        ["frFR"] = "Taille de la police des statistiques",
        ["zhCN"] = "统计字体大小",
    },
    ["RANGED_ATTACK_SPEED_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt das Fernkampf Angriffstempo.",
        ["enUS"] = "Shows/Hides the ranged attack speed.",
        ["frFR"] = "Shows/Hides the ranged attack speed.",
        ["zhCN"] = "Shows/Hides the ranged attack speed.",
    },
    ["PHYSICAL_CRIT"] = {
        ["deDE"] = "Physisch Kritisch: ",
        ["enUS"] = "Physical Crit: ",
        ["frFR"] = "Critique physique: ",
        ["zhCN"] = "物理暴击: ",
    },
    ["FIRE_DMG"] = {
        ["deDE"] = "Feuerschaden: ",
        ["enUS"] = "Fire Damage: ",
        ["frFR"] = "Dégats du feu: ",
        ["zhCN"] = "火焰伤害: ",
    },
    ["SPELL_POWER_SETTINGS"] = {
        ["deDE"] = "Zaubermacht",
        ["enUS"] = "Spell Power",
        ["frFR"] = "Puissance des sorts",
        ["zhCN"] = "法术强度",
    },
    ["SPELL_HIT_VALUES_SETTING"] = {
        ["deDE"] = "Zauber Trefferwertungen",
        ["enUS"] = "Spell Hit Values",
        ["frFR"] = "Val. de toucher sorts",
        ["zhCN"] = "法术命中率",
    },
    ["SPELL_POWER_STATS_SETTINGS"] = {
        ["deDE"] = "Zaubermachtwerte anzeigen",
        ["enUS"] = "Show Spell Power Stats",
        ["frFR"] = "Afficher la puissance des sorts",
        ["zhCN"] = "显示法术强度属性",
    },
    ["FIRE_CRIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance mit Feuerzaubern kritisch zu treffen.",
        ["enUS"] = "Shows/Hides the fire crit chance.",
        ["frFR"] = "Affiche/Cache les chances de critique du feu.",
        ["zhCN"] = "显示/隐藏 火焰暴击",
    },
    ["BLOCK_VALUE_SETTING"] = {
        ["deDE"] = "Blockwertung",
        ["enUS"] = "Block Value",
        ["frFR"] = "Bloquer",
        ["zhCN"] = "格挡值",
    },
    ["MOVEMENT_SPEED"] = {
        ["deDE"] = "Geschwindigkeit: ",
        ["enUS"] = "Movement Speed: ",
        ["frFR"] = "Vitesse de déplacement: ",
        ["zhCN"] = "移动速度: ",
    },
    ["COLORIZE_STATS_DESC"] = {
        ["deDE"] = "Fügt dem Wertefenster Farben hinzu.",
        ["enUS"] = "Adds colors to the stats overview.",
        ["frFR"] = "Ajoute des couleurs dans l'aperçu des statistiques.",
        ["zhCN"] = "添加颜色的统计概览。",
    },
    ["RANGED_HIT_RATING_SETTING_DESC"] = {
        ["enUS"] = "Shows/Hides the ranged hit rating.",
        ["deDE"] = "Zeigt/Versteckt die Fernkampf Trefferwertung.",
        ["zhCN"] = "Shows/Hides the ranged hit rating.",
    },
    ["SHADOW_DMG"] = {
        ["deDE"] = "Schattenschaden: ",
        ["enUS"] = "Shadow Damage: ",
        ["frFR"] = "Dégats des ombres: ",
        ["zhCN"] = "暗影伤害: ",
    },
    ["MP5_ITEMS"] = {
        ["deDE"] = "MP5 (Gegenstände): ",
        ["enUS"] = "MP5 (Items): ",
        ["frFR"] = "MP5 (Objets): ",
        ["zhCN"] = "装备回蓝: ",
    },
    ["BONUS"] = {
        ["deDE"] = "Bonus: ",
        ["enUS"] = "Bonus: ",
        ["frFR"] = "Bonus: ",
        ["zhCN"] = "命中: ",
    },
    ["RESILIENCE_SETTING"] = {
        ["deDE"] = "Abhärtung",
        ["enUS"] = "Resilience",
        ["frFR"] = "Résilience",
        ["zhCN"] = "Resilience",
    },
    ["RANGED_HIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt alle Trefferwertungen im Fernkampf.",
        ["enUS"] = "Shows/Hides all ranged hit chance.",
        ["frFR"] = "Affiche/cache les chances de toucher à distance.",
        ["zhCN"] = "显示/隐藏 所有远程命中",
    },
    ["STATS"] = {
        ["deDE"] = "Werte",
        ["enUS"] = "Stats",
        ["frFR"] = "Statistiques",
        ["zhCN"] = "统计信息",
    },
    ["FROST_DAMAGE_SETTING"] = {
        ["deDE"] = "Frostschaden",
        ["enUS"] = "Frost Damage",
        ["frFR"] = "Dégats du givre",
        ["zhCN"] = "冰霜伤害",
    },
    ["SELECT_LANGUAGE"] = {
        ["deDE"] = "Sprache",
        ["enUS"] = "Language",
        ["frFR"] = "Langue",
        ["zhCN"] = "语言",
    },
    ["CRIT_CHANCE"] = {
        ["deDE"] = "Kritische Chance: ",
        ["enUS"] = "Crit Chance: ",
        ["frFR"] = "Chances de critique: ",
        ["zhCN"] = "暴击几率: ",
    },
    ["MP5_BUFFS_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den MP5-Wert Stärkungszauber.",
        ["enUS"] = "Shows/Hides the MP5 value from buffs.",
        ["frFR"] = "Affiche/cache la valeur MP5 de Amélioration.",
        ["zhCN"] = "显示/隐藏 增益回蓝",
    },
    ["RANGED_SETTINGS_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt alle Fernkampfwerte.",
        ["enUS"] = "Shows/Hides all ranged stats.",
        ["frFR"] = "Affiche/cache toutes les statistiques à distance.",
        ["zhCN"] = "显示/隐藏 所有远程属性",
    },
    ["RANGED_SETTINGS"] = {
        ["deDE"] = "Fernkampfwerte anzeigen",
        ["enUS"] = "Show Ranged Stats",
        ["frFR"] = "À distance Général",
        ["zhCN"] = "显示远程属性",
    },
    ["RATING"] = {
        ["deDE"] = "Wertung: ",
        ["enUS"] = "Rating: ",
        ["frFR"] = "Rating: ",
        ["zhCN"] = "Rating: ",
    },
    ["NATURE_CRIT"] = {
        ["deDE"] = "Natur Kritisch: ",
        ["enUS"] = "Nature Crit: ",
        ["frFR"] = "Critique de la nature: ",
        ["zhCN"] = "自然暴击: ",
    },
    ["DEFENSE_RATING_SETTING"] = {
        ["deDE"] = "Verteidigungswertung",
        ["enUS"] = "Defense Rating",
        ["frFR"] = "Defense Rating",
        ["zhCN"] = "Defense Rating",
    },
    ["SPELL_CRIT_SETTING"] = {
        ["deDE"] = "Zauber Kritisch",
        ["enUS"] = "Spell Crit",
        ["frFR"] = "Critique des sorts",
        ["zhCN"] = "法术暴击",
    },
    ["HOLY_DAMAGE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Heiligschadenswert.",
        ["enUS"] = "Shows/Hides the holy damage value.",
        ["frFR"] = "Affiche/Cache les dégats du sacré.",
        ["zhCN"] = "显示/隐藏 神圣伤害",
    },
    ["FROST_DMG"] = {
        ["deDE"] = "Frostschaden: ",
        ["enUS"] = "Frost Damage: ",
        ["frFR"] = "Dégats du givre: ",
        ["zhCN"] = "冰霜伤害: ",
    },
    ["MP5_BUFFS"] = {
        ["deDE"] = "MP5 (Stärkungszauber): ",
        ["enUS"] = "MP5 (Buffs): ",
        ["frFR"] = "MP5 (Amélioration): ",
        ["zhCN"] = "增益回蓝: ",
    },
    ["DEFENSE_VALUE_SETTING"] = {
        ["deDE"] = "Verteidigung",
        ["enUS"] = "Defense Value",
        ["frFR"] = "Défense",
        ["zhCN"] = "防御",
    },
    ["HIT_RATING_SETTING"] = {
        ["deDE"] = "Trefferwertung",
        ["enUS"] = "Hit Rating",
        ["frFR"] = "Hit Rating",
        ["zhCN"] = "Hit Rating",
    },
    ["GENERAL_STATS_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die allgemeinen Werte.",
        ["enUS"] = "Shows/Hides all general stats.",
        ["frFR"] = "Affiche/cache toutes les statistiques générales.",
        ["zhCN"] = "显示/隐藏 所有常规属性信息。",
    },
    ["WINDOW_WIDTH_DESC"] = {
        ["deDE"] = "Ändert die Breite des Wertefensters",
        ["enUS"] = "Changes the width of the stats window",
        ["frFR"] = "Modifie la largeur de la fenêtre des statistiques",
        ["zhCN"] = "更改统计窗口的宽度",
    },
    ["MELEE_HIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt alle Trefferwertungen im Nahkampf.",
        ["enUS"] = "Shows/Hides all melee hit chance.",
        ["frFR"] = "Affiche/cache les chances de toucher en mêlée.",
        ["zhCN"] = "显示/隐藏 所有近战命中率",
    },
    ["MELEE_CRIT_SETTING"] = {
        ["deDE"] = "Nahkampf Kritisch",
        ["enUS"] = "Melee Crit",
        ["frFR"] = "Critique en mêlée",
        ["zhCN"] = "近战暴击",
    },
    ["MELEE_ATTACK_SPEED_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt das Angriffstempo im Nahkampf.",
        ["enUS"] = "Shows/Hides the melee attack speed.",
        ["frFR"] = "Shows/Hides the melee attack speed.",
        ["zhCN"] = "Shows/Hides the melee attack speed.",
    },
    ["GENERAL_SETTINGS"] = {
        ["deDE"] = "Allgemeine Einstellungen",
        ["enUS"] = "General Settings",
        ["frFR"] = "Paramètres généraux",
        ["zhCN"] = "一般设置",
    },
    ["HIT_BONUS_SETTING"] = {
        ["deDE"] = "Trefferwertungsbonus",
        ["enUS"] = "Hit Bonus",
        ["frFR"] = "Bonus de toucher",
        ["zhCN"] = "命中几率",
    },
    ["HIT"] = {
        ["deDE"] = "Trefferchance",
        ["enUS"] = "Hit",
        ["frFR"] = "Toucher",
        ["zhCN"] = "命中",
    },
    ["ARCANE_DAMAGE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Arkanschadenswert.",
        ["enUS"] = "Shows/Hides the arcane damage value.",
        ["frFR"] = "Affiche/Cache les dégats des arcanes.",
        ["zhCN"] = "显示/隐藏 奥术伤害",
    },
    ["PHYSICAL_DAMAGE_SETTING"] = {
        ["deDE"] = "Physischer Schaden",
        ["enUS"] = "Physical Damage",
        ["frFR"] = "Dégats physiques",
        ["zhCN"] = "物理伤害",
    },
    ["DEFENSE_RATING_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Verteidigungswertung.",
        ["enUS"] = "Shows/Hides the defense rating.",
        ["frFR"] = "Shows/Hides the defense rating.",
        ["zhCN"] = "Shows/Hides the defense rating.",
    },
    ["MELEE_MISS_CHANCE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance einen Gegner des gleichen Levels im Nahkampf zu verfehlen.",
        ["enUS"] = "Shows/Hides the melee miss chance against enemies on the same level.",
        ["frFR"] = "Affiche/cache les chances de rater en mêlée contre un ennemi du même niveau.",
        ["zhCN"] = "显示/隐藏 针对同等级敌人的近战未命中率",
    },
    ["MELEE_HIT_VALUES_SETTING"] = {
        ["deDE"] = "Nahkampf Trefferwertung",
        ["enUS"] = "Melee Hit Values",
        ["frFR"] = "Valeurs de toucher en mêlée",
        ["zhCN"] = "近战命中率",
    },
    ["MISS_BOSS"] = {
        ["deDE"] = "Verfehlen (Lvl + 3): ",
        ["enUS"] = "Miss (Lvl + 3): ",
        ["frFR"] = "Rater (Lvl + 3): ",
        ["zhCN"] = "未命中 (等级 + 3): ",
    },
    ["NAME_VERSION"] = {
        ["deDE"] = "ECS %s",
        ["enUS"] = "ECS %s",
        ["frFR"] = "ECS %s",
        ["zhCN"] = "ECS %s",
    },
    ["ATTACK_SPEED_HEADER"] = {
        ["deDE"] = "Angriffstempo",
        ["enUS"] = "Attack Speed",
        ["frFR"] = "Attack Speed",
        ["zhCN"] = "Attack Speed",
    },
    ["MELEE_ATTACK_POWER_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Nahkampf Angriffskraftwert.",
        ["enUS"] = "Shows/Hides the melee attack power value.",
        ["frFR"] = "Affiche/Cache la puissance d'attaque en mêlée.",
        ["zhCN"] = "显示/隐藏 近战攻击强度",
    },
    ["FROST_DAMAGE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Frostschadenswert.",
        ["enUS"] = "Shows/Hides the frost damage value.",
        ["frFR"] = "Affiche/Cache les dégats du givre.",
        ["zhCN"] = "显示/隐藏 冰霜伤害",
    },
    ["MOVEMENT_SPEED_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Bewegungsgeschwindigkeit.",
        ["enUS"] = "Shows/Hides the movement speed value.",
        ["frFR"] = "Affiche/Cache la vitesse de déplacement.",
        ["zhCN"] = "显示/隐藏 移动速度",
    },
    ["DEFENSE_SETTINGS_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt alle Verteidigungswerte.",
        ["enUS"] = "Shows/Hides all defense stats.",
        ["frFR"] = "Affiche/cache toutes les statistiques de défense.",
        ["zhCN"] = "显示/隐藏 所有防御属性",
    },
    ["COLORIZE_STATS"] = {
        ["deDE"] = "Werte färben",
        ["enUS"] = "Colorize Stats",
        ["frFR"] = "Coloriser les statistiques",
        ["zhCN"] = "染色统计信息",
    },
    ["RANGED_CRIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance im Fernkampf kritisch zu treffen.",
        ["enUS"] = "Shows/Hides the ranged crit chance.",
        ["frFR"] = "Affiche/cache les chances de coup critique à distance.",
        ["zhCN"] = "显示/隐藏 远程暴击",
    },
    ["MP5_BUFFS_SETTING"] = {
        ["deDE"] = "MP5 Stärkungszauber",
        ["enUS"] = "MP5 Buffs",
        ["frFR"] = "MP5 Amélioration",
        ["zhCN"] = "增益回蓝",
    },
    ["RANGED_ATTACK_SPEED_SETTING"] = {
        ["deDE"] = "Angriffstempo",
        ["enUS"] = "Attack Speed",
        ["frFR"] = "Attack Speed",
        ["zhCN"] = "Attack Speed",
    },
    ["MISS"] = {
        ["deDE"] = "Verfehlen: ",
        ["enUS"] = "Miss: ",
        ["frFR"] = "Rater: ",
        ["zhCN"] = "未命中: ",
    },
    ["MOVEMENT_SPEED_SETTING"] = {
        ["deDE"] = "Bewegungsgeschwindigkeit anzeigen",
        ["enUS"] = "Show Movement Speed",
        ["frFR"] = "Affiche la vitesse de déplacement",
        ["zhCN"] = "显示移动速度",
    },
    ["CRIT_IMMUNITY_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die erreichte Crit Immunität in Prozent.",
        ["enUS"] = "Shows/Hides the percentage of being crit immune.",
        ["frFR"] = "Shows/Hides the percentage of being crit immune.",
        ["zhCN"] = "Shows/Hides the percentage of being crit immune.",
    },
    ["ATTACK_SPEED_OFF_HAND"] = {
        ["deDE"] = "Schildhand: ",
        ["enUS"] = "Off Hand: ",
        ["frFR"] = "Off Hand: ",
        ["zhCN"] = "Off Hand: ",
    },
    ["PARRY_CHANCE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Parrierwertung.",
        ["enUS"] = "Shows/Hides the parry chance.",
        ["frFR"] = "Affiche/cache les chances de parer.",
        ["zhCN"] = "显示/隐藏 招架几率",
    },
    ["RANGED_CRIT_SETTING"] = {
        ["deDE"] = "Fernkampf Kritisch",
        ["enUS"] = "Ranged Crit",
        ["frFR"] = "Critique à distance",
        ["zhCN"] = "远程暴击",
    },
    ["ATTACK_SPEED"] = {
        ["deDE"] = "Attack Speed: ",
        ["enUS"] = "Attack Speed: ",
        ["frFR"] = "Attack Speed: ",
        ["zhCN"] = "Attack Speed: ",
    },
    ["GENERAL_STATS"] = {
        ["deDE"] = "Allgemeine Werte anzeigen",
        ["enUS"] = "Show General Stats",
        ["frFR"] = "Général",
        ["zhCN"] = "显示常规属性信息",
    },
    ["BLOCK_CHANCE_SETTING"] = {
        ["deDE"] = "Blockchance",
        ["enUS"] = "Block Chance",
        ["frFR"] = "Chances de bloquer",
        ["zhCN"] = "格挡几率",
    },
    ["BLOCK_VALUE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Blockwertung.",
        ["enUS"] = "Shows/Hides the block value.",
        ["frFR"] = "Affiche/cache la valeur de bloquage.",
        ["zhCN"] = "显示/隐藏 格挡值",
    },
    ["BLOCK_CHANCE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Blockchance.",
        ["enUS"] = "Shows/Hides the block chance.",
        ["frFR"] = "Affiche/cache les chances de bloquer.",
        ["zhCN"] = "显示/隐藏 格挡几率",
    },
    ["DEFENSE_RATING"] = {
        ["deDE"] = "Verteidigungswertung: ",
        ["enUS"] = "Defense Rating: ",
        ["frFR"] = "Defense Rating: ",
        ["zhCN"] = "Defense Rating: ",
    },
    ["MELEE_ATTACK_SPEED_MAIN_HAND_SETTING"] = {
        ["deDE"] = "Waffenhand",
        ["enUS"] = "Main Hand",
        ["frFR"] = "Main Hand",
        ["zhCN"] = "Main Hand",
    },
    ["MELEE_SETTINGS"] = {
        ["deDE"] = "Nahkampfwerte anzeigen",
        ["enUS"] = "Show Melee Stats",
        ["frFR"] = "Mêlée Général",
        ["zhCN"] = "显示近战属性",
    },
    ["SHADOW_CRIT"] = {
        ["deDE"] = "Schatten Kritisch: ",
        ["enUS"] = "Shadow Crit: ",
        ["frFR"] = "Critique des ombres: ",
        ["zhCN"] = "暗影暴击: ",
    },
    ["MP5_ITEMS_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den MP5-Wert von Gegenständen.",
        ["enUS"] = "Shows/Hides the MP5 value from items.",
        ["frFR"] = "Affiche/cache la valeur MP5 des objets.",
        ["zhCN"] = "显示/隐藏 装备回蓝",
    },
    ["ARMOR_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Rüstungswert.",
        ["enUS"] = "Shows/Hides the armor value.",
        ["frFR"] = "Affiche/cache la valeur de l'armure.",
        ["zhCN"] = "显示/隐藏 护甲值",
    },
    ["CRIT_IMMUNITY"] = {
        ["deDE"] = "Krit. Immun: ",
        ["enUS"] = "Crit Immune: ",
        ["frFR"] = "Crit Immune: ",
        ["zhCN"] = "Crit Immune: ",
    },
    ["MISS_CHANCE_SETTING"] = {
        ["deDE"] = "Chance zu verfehlen",
        ["enUS"] = "Miss Chance",
        ["frFR"] = "Chances de rater",
        ["zhCN"] = "未命中几率",
    },
    ["STATS_SETTINGS"] = {
        ["deDE"] = "Werte Einstellungen",
        ["enUS"] = "Stats Settings",
        ["frFR"] = "Paramètres des statistiques",
        ["zhCN"] = "统计信息设置",
    },
    ["PARRY_CHANCE"] = {
        ["deDE"] = "Parrierchance: ",
        ["enUS"] = "Parry Chance: ",
        ["frFR"] = "Chances de parrer: ",
        ["zhCN"] = "招架几率: ",
    },
    ["FIRE_DAMAGE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Feuerschadenswert.",
        ["enUS"] = "Shows/Hides the fire damage value.",
        ["frFR"] = "Affiche/Cache les dégats du feu.",
        ["zhCN"] = "显示/隐藏 火焰伤害",
    },
    ["CRIT_REDUCTION"] = {
        ["deDE"] = "Krit. Reduzierung: ",
        ["enUS"] = "Crit Reduction: ",
        ["frFR"] = "Crit Reduction: ",
        ["zhCN"] = "Crit Reduction: ",
    },
    ["SPELL_POWER"] = {
        ["deDE"] = "Zauberkraft",
        ["enUS"] = "Spell Power",
        ["frFR"] = "Puissance des sorts",
        ["zhCN"] = "法术强度",
    },
    ["MP5_SPIRIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den MP5-Wert durch Willenskraft.",
        ["enUS"] = "Shows/Hides the MP5 value from spirit.",
        ["frFR"] = "Affiche/cache la valeur MP5 de l'esprit.",
        ["zhCN"] = "显示/隐藏 精神回蓝",
    },
    ["SHADOW_DAMAGE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Schattenschadenswert.",
        ["enUS"] = "Shows/Hides the shadow damage value.",
        ["frFR"] = "Affiche/Cache les dégats des ombres.",
        ["zhCN"] = "显示/隐藏 暗影伤害",
    },
    ["AVAILABLE_COMMANDS"] = {
        ["deDE"] = "Verfügbare Befehle",
        ["enUS"] = "Available Commands",
        ["frFR"] = "Commandes disponibles",
        ["zhCN"] = "可以命令",
    },
    ["STAT_TEXTS"] = {
        ["deDE"] = "Wertenamen",
        ["enUS"] = "Stat texts",
        ["frFR"] = "Textes des statistiques",
        ["zhCN"] = "统计文本染色",
    },
    ["ATTACK_SPEED_MAIN_HAND"] = {
        ["deDE"] = "Waffenhand: ",
        ["enUS"] = "Main Hand: ",
        ["frFR"] = "Main Hand: ",
        ["zhCN"] = "Main Hand: ",
    },
    ["DODGE_CHANCE_SETTING"] = {
        ["deDE"] = "Ausweichchance",
        ["enUS"] = "Dodge Chance",
        ["frFR"] = "Chances d'esquiver",
        ["zhCN"] = "躲闪",
    },
    ["GENERAL"] = {
        ["deDE"] = "Allgemein",
        ["enUS"] = "General",
        ["frFR"] = "Général",
        ["zhCN"] = "一般",
    },
    ["HOLY_CRIT"] = {
        ["deDE"] = "Heilig Kritisch: ",
        ["enUS"] = "Holy Crit: ",
        ["frFR"] = "Critique du sacré: ",
        ["zhCN"] = "神圣暴击: ",
    },
    ["HEALING_POWER"] = {
        ["deDE"] = "Heilungskraft: ",
        ["enUS"] = "Healing Power: ",
        ["frFR"] = "Puissance des soins: ",
        ["zhCN"] = "法术治疗: ",
    },
    ["RESILIENCE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Abhärtungswert.",
        ["enUS"] = "Shows/Hides the resilience value.",
        ["frFR"] = "Affiche/cache la valeur de résilience.",
        ["zhCN"] = "Shows/Hides the resilience value.",
    },
    ["NATURE_CRIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance mit Naturzaubern kritisch zu treffen.",
        ["enUS"] = "Shows/Hides the nature crit chance.",
        ["frFR"] = "Affiche/Cache les chances de critique de la nature.",
        ["zhCN"] = "显示/隐藏 自然暴击",
    },
    ["FIRE_CRIT"] = {
        ["deDE"] = "Feuer Kritisch: ",
        ["enUS"] = "Fire Crit: ",
        ["frFR"] = "Critique du feu: ",
        ["zhCN"] = "火焰暴击: ",
    },
    ["RANGED_HIT_SETTING"] = {
        ["deDE"] = "Fernkampf Trefferwertung",
        ["enUS"] = "Ranged Hit",
        ["frFR"] = "Toucher à distance",
        ["zhCN"] = "远程命中",
    },
    ["CRIT_REDUCTION_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt, um wie viel Prozent die Chance kritisch getroffen zu werden reduziert ist.",
        ["enUS"] = "Shows/Hides the reduction percentage of being critically hit.",
        ["frFR"] = "Shows/Hides the reduction percentage of being critically hit.",
        ["zhCN"] = "Shows/Hides the reduction percentage of being critically hit.",
    },
    ["SLASH_CONFIG"] = {
        ["deDE"] = "/ecs config",
        ["enUS"] = "/ecs config",
        ["frFR"] = "/ecs config",
        ["zhCN"] = "/ecs config",
    },
    ["MP5_CASTING_SETTING"] = {
        ["deDE"] = "MP5 Zaubernd",
        ["enUS"] = "MP5 Casting",
        ["frFR"] = "MP5 Lancer",
        ["zhCN"] = "附魔回蓝",
    },
    ["MP5_CASTING_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den MP5-Wert während des Zauberwirkens.",
        ["enUS"] = "Shows/Hides the MP5 while casting value.",
        ["frFR"] = "Affiche/cache la valeur MP5 pendant le lancer.",
        ["zhCN"] = "显示/隐藏 附魔回蓝",
    },
    ["ARCANCE_DMG"] = {
        ["deDE"] = "Arkanschaden: ",
        ["enUS"] = "Arcane Damage: ",
        ["frFR"] = "Dégats des arcanes: ",
        ["zhCN"] = "奥术伤害: ",
    },
    ["STAT_VALUES"] = {
        ["deDE"] = "Wertezahlen",
        ["enUS"] = "Stat values",
        ["frFR"] = "Valeurs des statistiques",
        ["zhCN"] = "属性染色",
    },
    ["SPELL_MISS_CHANCE_BOSS_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance einen Gegner mit 3 Level über dem eigenen mit Zauber zu verfehlen.",
        ["enUS"] = "Shows/Hides the spell miss chance against boss enemies (+3 Level).",
        ["frFR"] = "Affiche/cache les chances de rater des sorts contre un boss de 3 niveaux supérieurs.",
        ["zhCN"] = "显示/隐藏 针对BOSS的法术未命中率 (+3 等级)。",
    },
    ["HEADER_FONT_SIZE_DESC"] = {
        ["deDE"] = "Ändert die Schriftgröße der Überschriften (z.B. Nahkampf)",
        ["enUS"] = "Changes the font size of the headers (e.g. Melee)",
        ["frFR"] = "Modifie la taille de la police d'entête (ex. Mêlée)",
        ["zhCN"] = "更改标题的字体大小 (例如：近战)",
    },
    ["STAT_FONT_SIZE_DESC"] = {
        ["deDE"] = "Ändert die Schriftgröße der Werte (z.B. Kritische Chance)",
        ["enUS"] = "Changes the font size of the stat lines (e.g. Crit)",
        ["frFR"] = "Modifie la taille de la police des statistiques (ex. Critique)",
        ["zhCN"] = "更改统计行的字体大小 (例如：暴击)",
    },
    ["FULL"] = {
        ["deDE"] = "Komplett",
        ["enUS"] = "Full",
        ["frFR"] = "Toutes",
        ["zhCN"] = "全部",
    },
    ["SPELL_SETTINGS_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt alle Zauberwerte.",
        ["enUS"] = "Shows/Hides all spell stats.",
        ["frFR"] = "Affiche/cache toutes les statistiques des sorts.",
        ["zhCN"] = "显示/隐藏 法术属性",
    },
    ["CRIT_IMMUNITY_SETTING"] = {
        ["deDE"] = "Krit. Immun",
        ["enUS"] = "Crit Immune",
        ["frFR"] = "Crit Immune",
        ["zhCN"] = "Crit Immune",
    },
    ["RANGED_ATTACK_POWER_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Fernkampf Angriffskraftwert.",
        ["enUS"] = "Shows/Hides the ranged attack power value.",
        ["frFR"] = "Affiche/Cache la puissance d'attaque à distance.",
        ["zhCN"] = "显示/隐藏 远程攻击强度",
    },
    ["MELEE"] = {
        ["deDE"] = "Nahkampf",
        ["enUS"] = "Melee",
        ["frFR"] = "Mêlée",
        ["zhCN"] = "近战",
    },
    ["NATURE_DAMAGE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Naturschadenswert.",
        ["enUS"] = "Shows/Hides the nature damage value.",
        ["frFR"] = "Affiche/Cache les dégats de la nature.",
        ["zhCN"] = "显示/隐藏 自然伤害",
    },
    ["MP5_ITEMS_SETTING"] = {
        ["deDE"] = "MP5 Gegenstände",
        ["enUS"] = "MP5 Items",
        ["frFR"] = "MP5 Objets",
        ["zhCN"] = "装备回蓝 ",
    },
    ["MP5_SPIRIT_SETTING"] = {
        ["deDE"] = "MP5 Willenskraft",
        ["enUS"] = "MP5 Spirit",
        ["frFR"] = "MP5 Esprit",
        ["zhCN"] = "精神回蓝",
    },
    ["SPELL_SETTINGS"] = {
        ["deDE"] = "Zauberwerte anzeigen",
        ["enUS"] = "Show Spell Stats",
        ["frFR"] = "Sorts Général",
        ["zhCN"] = "显示法术属性",
    },
    ["SPELL_HIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt alle Trefferwertungswertungen für Zauber.",
        ["enUS"] = "Shows/Hides all spell hit chance.",
        ["frFR"] = "Affiche/cache les chances de toucher avec les sorts.",
        ["zhCN"] = "显示/隐藏 法术命中",
    },
    ["MELEE_MISS_CHANCE_BOSS_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance einen Gegner mit 3 Level über dem eigenen im Nahkampf zu verfehlen.",
        ["enUS"] = "Shows/Hides the melee miss chance against boss enemies (+3 Level).",
        ["frFR"] = "Affiche/cache les chances de rater en mêlée contre un boss de 3 niveaux supérieurs.",
        ["zhCN"] = "显示/隐藏 针对BOSS的近战未命中率 (+3 等级)。",
    },
    ["HEADER_FONT_SIZE"] = {
        ["deDE"] = "Überschriften Schriftgröße",
        ["enUS"] = "Header Font Size",
        ["frFR"] = "Taille de la police d'entête",
        ["zhCN"] = "标题字体大小",
    },
    ["PHYSICAL_CRIT_SETTING"] = {
        ["deDE"] = "Physisch Kritisch",
        ["enUS"] = "Physical Crit",
        ["frFR"] = "Critique physiques",
        ["zhCN"] = "物理暴击",
    },
    ["ARCANCE_CRIT"] = {
        ["deDE"] = "Arkan Kritisch: ",
        ["enUS"] = "Arcane Crit: ",
        ["frFR"] = "Critique des arcanes: ",
        ["zhCN"] = "奥术暴击: ",
    },
    ["MELEE_ATTACK_POWER_SETTING"] = {
        ["deDE"] = "Nahkampf Angriffskraft",
        ["enUS"] = "Melee Attack Power",
        ["frFR"] = "Puissance d'attaque en mêlée",
        ["zhCN"] = "近战攻击强度",
    },
    ["MELEE_EXPERTISE_SETTING"] = {
        ["deDE"] = "Waffenkundewertung",
        ["enUS"] = "Expertise",
        ["frFR"] = "Expertise",
        ["zhCN"] = "Expertise",
    },
    ["MELEE_HIT_BONUS_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Bonus auf die Nahkampf Trefferwertung.",
        ["enUS"] = "Shows/Hides the melee hit bonus.",
        ["frFR"] = "Affiche/Cache le bonus de toucher.",
        ["zhCN"] = "显示/隐藏 近战命中率",
    },
    ["BLOCK_VALUE"] = {
        ["deDE"] = "Blockwertung: ",
        ["enUS"] = "Block Value: ",
        ["frFR"] = "Bloquage: ",
        ["zhCN"] = "格挡值: ",
    },
    ["SPELL_HIT_RATING_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Zauber Trefferwertung.",
        ["enUS"] = "Shows/Hides the spell hit rating.",
        ["frFR"] = "Shows/Hides the spell hit rating.",
        ["zhCN"] = "Shows/Hides the spell hit rating.",
    },
    ["FROST_CRIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance mit Frostzaubern kritisch zu treffen.",
        ["enUS"] = "Shows/Hides the frost crit chance.",
        ["frFR"] = "Affiche/Cache les chances de critique du givre.",
        ["zhCN"] = "显示/隐藏 冰霜暴击",
    },
    ["MANA_SETTINGS"] = {
        ["deDE"] = "Manawerte anzeigen",
        ["enUS"] = "Show Mana Stats",
        ["frFR"] = "Mana Général",
        ["zhCN"] = "显示法力回复",
    },
    ["PHYSICAL_DMG"] = {
        ["deDE"] = "Physischer Schaden: ",
        ["enUS"] = "Physical Damage: ",
        ["frFR"] = "Dégats physiques: ",
        ["zhCN"] = "物理伤害: ",
    },
    ["HEALING_POWER_SETTING"] = {
        ["deDE"] = "Heilungsmacht",
        ["enUS"] = "Healing Power",
        ["frFR"] = "Puissance des soins",
        ["zhCN"] = "法术治疗",
    },
    ["HEALING_POWER_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den Heilungsmachtwert.",
        ["enUS"] = "Shows/Hides the healing power value.",
        ["frFR"] = "Affiche/Cache la puissance des soins.",
        ["zhCN"] = "显示/隐藏 法术治疗",
    },
    ["FIRE_CRIT_SETTING"] = {
        ["deDE"] = "Feuer Kritisch",
        ["enUS"] = "Fire Crit",
        ["frFR"] = "Critique du feu",
        ["zhCN"] = "火焰暴击",
    },
    ["SPELL_MISS_CHANCE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance einen Gegner des gleichen Levels mit Zauber zu verfehlen.",
        ["enUS"] = "Shows/Hides the spell miss chance against enemies on the same level.",
        ["frFR"] = "Affiche/cache les chances de rater des sorts contre un ennemi du même niveau.",
        ["zhCN"] = "显示/隐藏 针对同等级敌人的法术未命中率",
    },
    ["ARMOR"] = {
        ["deDE"] = "Rüstung: ",
        ["enUS"] = "Armor: ",
        ["frFR"] = "Armure: ",
        ["zhCN"] = "护甲: ",
    },
    ["SETTINGS"] = {
        ["deDE"] = "Einstellungen",
        ["enUS"] = "Settings",
        ["frFR"] = "Paramètres",
        ["zhCN"] = "设置",
    },
    ["MELEE_ATTACK_SPEED_OFF_HAND_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt das Angriffstempo der Schildhand.",
        ["enUS"] = "Shows/Hides the attack speed of the off hand.",
        ["frFR"] = "Shows/Hides the attack speed of the off hand.",
        ["zhCN"] = "Shows/Hides the attack speed of the off hand.",
    },
    ["ATTACK_POWER"] = {
        ["deDE"] = "Angriffskraft: ",
        ["enUS"] = "Attack Power: ",
        ["frFR"] = "Puissance d'attaque: ",
        ["zhCN"] = "攻击强度: ",
    },
    ["SLASH_CONFIG_DESC"] = {
        ["deDE"] = "Öffnet/Schließt das Einstellungsfenster",
        ["enUS"] = "Shows the configuration window",
        ["frFR"] = "Affiche la fenêtre de configuration ECS",
        ["zhCN"] = "显示配置窗口",
    },
    ["HOLY_CRIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance mit Heiligzaubern kritisch zu treffen.",
        ["enUS"] = "Shows/Hides the holy crit chance.",
        ["frFR"] = "Affiche/Cache les chances de critique du sacré.",
        ["zhCN"] = "显示/隐藏 神圣暴击",
    },
    ["NATURE_DAMAGE_SETTING"] = {
        ["deDE"] = "Naturschaden",
        ["enUS"] = "Nature Damage",
        ["frFR"] = "Dégats de la nature",
        ["zhCN"] = "自然伤害",
    },
    ["RANGED_ATTACK_POWER_SETTING"] = {
        ["deDE"] = "Fernkampf Angriffskraft",
        ["enUS"] = "Melee Attack Power",
        ["frFR"] = "Puissance d'attaque à distance",
        ["zhCN"] = "远程攻击强度",
    },
    ["NATURE_CRIT_SETTING"] = {
        ["deDE"] = "Natur Kritisch",
        ["enUS"] = "Nature Crit",
        ["frFR"] = "Critique de la nature",
        ["zhCN"] = "自然暴击",
    },
    ["STATS_WINDOW_CLOSED"] = {
        ["deDE"] = "Verstecke das ECS Fenster beim Öffnen des Charakterfensters",
        ["enUS"] = "Hide ECS when opening character tab",
        ["frFR"] = "Cache ECS quand la fenêtre du personnage est ouverte",
        ["zhCN"] = "显示ECS切换按键",
    },
    ["RANGED_HIT_VALUES_SETTING"] = {
        ["deDE"] = "Fernkampf Trefferwertungen",
        ["enUS"] = "Ranged Hit Values",
        ["frFR"] = "Valeurs de toucher à dist.",
        ["zhCN"] = "远程命中率",
    },
    ["MELEE_EXPERTISE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Waffenkundewertung.",
        ["enUS"] = "Shows/Hides the expertise value.",
        ["frFR"] = "Shows/Hides the expertise value.",
        ["zhCN"] = "Shows/Hides the expertise value.",
    },
    ["SHADOW_DAMAGE_SETTING"] = {
        ["deDE"] = "Schattenschaden",
        ["enUS"] = "Shadow Damage",
        ["frFR"] = "Dégats des ombres",
        ["zhCN"] = "暗影伤害",
    },
    ["SPELL"] = {
        ["deDE"] = "Zauber",
        ["enUS"] = "Spell",
        ["frFR"] = "Sorts",
        ["zhCN"] = "法术强度",
    },
    ["MELEE_CRIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance im Nahkampf kritisch zu treffen.",
        ["enUS"] = "Shows/Hides the melee crit chance.",
        ["frFR"] = "Affiche/cache les chances d'infliger un coup critique en mêlée.",
        ["zhCN"] = "显示/隐藏 近战暴击几率",
    },
    ["MELEE_HIT_RATING_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Nahkampf Trefferwertung.",
        ["enUS"] = "Shows/Hides the melee hit rating.",
        ["frFR"] = "Shows/Hides the melee hit rating.",
        ["zhCN"] = "Shows/Hides the melee hit rating.",
    },
    ["RANGED_MISS_CHANCE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance einen Gegner des gleichen Levels im Fernkampf zu verfehlen.",
        ["enUS"] = "Shows/Hides the ranged miss chance against enemies on the same level.",
        ["frFR"] = "Affiche/cache les chances de rater à distance contre un ennemi du même niveau.",
        ["zhCN"] = "显示/隐藏 针对同等级敌人的远程未命中率",
    },
    ["ARMOR_SETTING"] = {
        ["deDE"] = "Rüstung",
        ["enUS"] = "Armor Value",
        ["frFR"] = "Armure",
        ["zhCN"] = "护甲",
    },
    ["SHADOW_CRIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance mit Schattenzaubern kritisch zu treffen.",
        ["enUS"] = "Shows/Hides the shadow crit chance.",
        ["frFR"] = "Affiche/Cache les chances de critique des ombres.",
        ["zhCN"] = "显示/隐藏 暗影暴击",
    },
    ["HOLY_DAMAGE_SETTING"] = {
        ["deDE"] = "Heiligschaden",
        ["enUS"] = "Holy Damage",
        ["frFR"] = "Dégats du sacré",
        ["zhCN"] = "神圣伤害",
    },
    ["SELECT_STAT_COLORS"] = {
        ["deDE"] = "Werte Farbe",
        ["enUS"] = "Stats colorization",
        ["frFR"] = "Couleurs des statistiques",
        ["zhCN"] = "统计信息染色",
    },
    ["ARCANE_CRIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance mit Arkanzaubern kritisch zu treffen.",
        ["enUS"] = "Shows/Hides the arcane crit chance.",
        ["frFR"] = "Affiche/Cache les chances de critique des arcanes.",
        ["zhCN"] = "显示/隐藏 奥术暴击",
    },
    ["MANA_SETTINGS_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt alle Manawerte.",
        ["enUS"] = "Shows/Hides all mana stats.",
        ["frFR"] = "Affiche/cache toutes les statistiques de mana.",
        ["zhCN"] = "显示/隐藏 所有法力回复",
    },
    ["MELEE_HIT_SETTING"] = {
        ["deDE"] = "Nahkampf Trefferwertung",
        ["enUS"] = "Melee Hit",
        ["frFR"] = "Toucher en mêlée",
        ["zhCN"] = "近战命中",
    },
    ["PHYSICAL_DAMAGE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt den physischen Schadenswert.",
        ["enUS"] = "Shows/Hides the physical damage value.",
        ["frFR"] = "Affiche/Cache les dégats physiques.",
        ["zhCN"] = "显示/隐藏 物理伤害",
    },
    ["SPELL_PENETRATION"] = {
        ["deDE"] = "Durchschlagskraft: ",
        ["enUS"] = "Penetration: ",
        ["frFR"] = "Penetration: ",
        ["zhCN"] = "Penetration: ",
    },
    ["SPELL_CRIT_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Chance mit einem Zauber kritisch zu treffen.",
        ["enUS"] = "Shows/Hides the spell crit chance.",
        ["frFR"] = "Affiche/cache les chances d'infliger un coup critique avec les sorts.",
        ["zhCN"] = "显示/隐藏 法术暴击",
    },
    ["ARCANE_DAMAGE_SETTING"] = {
        ["deDE"] = "Arkanschaden",
        ["enUS"] = "Arcane Damage",
        ["frFR"] = "Dégats des arcanes",
        ["zhCN"] = "奥术伤害",
    },
    ["HOLY_CRIT_SETTING"] = {
        ["deDE"] = "Heilig Kritisch",
        ["enUS"] = "Holy Crit",
        ["frFR"] = "Critique du sacré",
        ["zhCN"] = "神圣暴击",
    },
    ["MELEE_ATTACK_SPEED_MAIN_HAND_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt das Angriffstempo der Waffenhand.",
        ["enUS"] = "Shows/Hides the attack speed of the main hand.",
        ["frFR"] = "Shows/Hides the attack speed of the main hand.",
        ["zhCN"] = "Shows/Hides the attack speed of the main hand.",
    },
    ["FIRE_DAMAGE_SETTING"] = {
        ["deDE"] = "Feuerschaden",
        ["enUS"] = "Fire Damage",
        ["frFR"] = "Dégats du feu",
        ["zhCN"] = "火焰伤害",
    },
    ["WINDOW_WIDTH"] = {
        ["deDE"] = "Fensterbreite",
        ["enUS"] = "Window Width",
        ["frFR"] = "Largeur de fenêtre",
        ["zhCN"] = "窗口宽度",
    },
    ["PARRY_CHANCE_SETTING"] = {
        ["deDE"] = "Parrierwertung",
        ["enUS"] = "Parry Chance",
        ["frFR"] = "Chances de parer",
        ["zhCN"] = "招架",
    },
    ["SLASH_TOGGLE_DESC"] = {
        ["deDE"] = "Öffnet/Schließt das Attributefenster",
        ["enUS"] = "Toggles the visibility of the stats window",
        ["frFR"] = "Affiche/Cache la fenêtre des statistiques ECS",
        ["zhCN"] = "切换统计信息窗口",
    },
    ["RANGED"] = {
        ["deDE"] = "Fernkampf",
        ["enUS"] = "Ranged",
        ["frFR"] = "A distance",
        ["zhCN"] = "远程",
    },
    ["RESILIENCE_VALUE"] = {
        ["deDE"] = "Abhärtung: ",
        ["enUS"] = "Resilience: ",
        ["frFR"] = "Résilience: ",
        ["zhCN"] = "Resilience: ",
    },
    ["SPELL_PENETRATION_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die Zauberdurchschlagskraft.",
        ["enUS"] = "Shows/Hides the spell penetration value.",
        ["frFR"] = "Shows/Hides the spell penetration value.",
        ["zhCN"] = "Shows/Hides the spell penetration value.",
    },
    ["DEFENSE_VALUE_SETTING_DESC"] = {
        ["deDE"] = "Zeigt/Versteckt die den Verteidigungswert.",
        ["enUS"] = "Shows/Hides the defense value.",
        ["frFR"] = "Affiche/cache la valeur de défense.",
        ["zhCN"] = "显示/隐藏 防御值",
    },
}
